{% set name = "emc2" %}
{% set version = "1.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emc2-{{ version }}.tar.gz
  sha256: c5aa682356d33bd253be005486590d17397135dd93e230057da9100fc4bc929b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - python <3.12
  run:
    - python >=3.9
    - python <3.12
    - xarray
    - matplotlib-base
    - dask
    - pint
    - act-atmos
    - cython
test:
  imports:
    - emc2
    - emc2.core
  commands:
    - pip install icartt
    - pip check
  requires:
    - pip

about:
  home: https://github.com/columncolab/EMC2
  summary: An open source framework for atmospheric model and observational column comparison.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rcjackson
