{% set name = "emc2" %}
{% set version = "1.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emc2-{{ version }}.tar.gz
  sha256: 1ac9801e86264ac4f3c8f6eb90382f72857544931df334686d44fe8216ef7442

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - xarray
    - matplotlib-base
    - dask
    - pint
    - act-atmos
    - arm_pyart
    - cython
test:
  imports:
    - emc2
    - emc2.core
  commands:
    - pip install icartt
    - pip check
  requires:
    - pip

about:
  home: https://github.com/columncolab/EMC2
  summary: An open source framework for atmospheric model and observational column comparison.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rcjackson
