{% set name = "emc2" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emc2-{{ version }}.tar.gz
  sha256: bbf3c1f343d3c104f8089d7e4fe3055970bca8cde338925f624f345b9b9b206d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - xarray
    - matplotlib-base
    - dask
    - pint
    - act-atmos
test:
  imports:
    - emc2
    - emc2.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/columncolab/EMC2
  summary: An open source framework for atmospheric model and observational column comparison.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rcjackson
